server:
  port: 8888
spring:
  application:
    name: eureka-server
    # 集群版配置
eureka:
#  instance:
#  hostname: localhost
  client:
    register-with-eureka: false # 是否需要把该服务注册到Eureka
    fetch-registry: false # 是否需要从Eureka获取注册信息
    service-url:  # 暴露Eureka注册地址
      defaultZone: http://localhost:8888/eureka
